### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by metakalis** [liushengxian/soup-js#1]
i need help about rub script !!

i have this error

module.js:487
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/Desktop/Call-Flooder/server.js:1:77)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

**Comment by liushengxian** [comment]
Seems that you cannot find module 'express'.
Simply run 'npm install --save express' in your terminal, you will solve this problem.
Actually I don't use express in my code.
